# Generated by Django 3.1.7 on 2021-02-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='date_joined',
            field=models.DateField(null=True),
        ),
    ]
